version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  nginx:
    container_name: "nginx"
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=kimetsu
    ports:
      - "27017:27017" # remove this line on prod