version: '3'

services:
  db:
    image: mongo
    restart: always
    env_file:
      - .env
  web_app:
    build:
      dockerfile: Dockerfile
      context: .
#    command:
#      - "uvicorn app.main:app --port 8000 --reload"
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"