version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_DATABASE: kimetsu
    ports:
      - 27017:27017 # remove this line on prod